create table if not exists public.documentos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  vigencia text not null,
  categoria text not null,
  fecha date not null default current_date,
  estado text not null default 'Publicado',
  entidad text not null,
  descripcion text,
  archivo_path text,
  archivo_url text,
  archivo_nombre text,
  metadatos jsonb not null default '{}'::jsonb,
  publico boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.documentos enable row level security;

create policy "Public can read public documents"
on public.documentos
for select
using (publico = true);

create policy "Authenticated users can manage documents"
on public.documentos
for all
to authenticated
using (true)
with check (true);

insert into storage.buckets (id, name, public)
values ('documentos', 'documentos', true)
on conflict (id) do nothing;

create policy "Public can read document files"
on storage.objects
for select
using (bucket_id = 'documentos');

create policy "Authenticated users can upload document files"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'documentos');

create policy "Authenticated users can update document files"
on storage.objects
for update
to authenticated
using (bucket_id = 'documentos')
with check (bucket_id = 'documentos');

create policy "Authenticated users can delete document files"
on storage.objects
for delete
to authenticated
using (bucket_id = 'documentos');

create table if not exists public.instrumentos_planeacion (
  id bigint generated by default as identity primary key,
  nombre text not null,
  tipo text not null,
  eje text not null,
  fecha_inicio text not null,
  fecha_fin text not null,
  estado text not null,
  link text not null,
  enlace_web text not null,
  documento_url text,
  observatorio text,
  visible boolean not null default false,
  validacion_errores jsonb not null default '[]'::jsonb,
  origen text not null default 'admin',
  source_row integer,
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create index if not exists instrumentos_planeacion_visible_idx
on public.instrumentos_planeacion (visible);

create index if not exists instrumentos_planeacion_estado_idx
on public.instrumentos_planeacion (estado);

create or replace function public.set_fecha_actualizacion()
returns trigger as $$
begin
  new.fecha_actualizacion = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists instrumentos_planeacion_set_fecha_actualizacion on public.instrumentos_planeacion;
create trigger instrumentos_planeacion_set_fecha_actualizacion
before update on public.instrumentos_planeacion
for each row execute function public.set_fecha_actualizacion();

alter table public.instrumentos_planeacion enable row level security;

drop policy if exists "Public can read visible planning instruments" on public.instrumentos_planeacion;
create policy "Public can read visible planning instruments"
on public.instrumentos_planeacion
for select
using (visible = true and jsonb_array_length(validacion_errores) = 0);

drop policy if exists "Authenticated users can manage planning instruments" on public.instrumentos_planeacion;
create policy "Authenticated users can manage planning instruments"
on public.instrumentos_planeacion
for all
to authenticated
using (true)
with check (true);
