-- Seed generated from Base de datos Instrumentos Planeacion.xlsx
-- Records: 55

insert into public.instrumentos_planeacion (
  nombre,
  tipo,
  eje,
  fecha_inicio,
  fecha_fin,
  estado,
  link,
  enlace_web,
  documento_url,
  observatorio,
  visible,
  validacion_errores,
  origen,
  source_row
) values
(
  'VISION CALI 500+',
  'Instrumentos Macro',
  'Transversal',
  '2024',
  '2050',
  'En Ejecución',
  '0.VISION CALI 500+.pdf',
  'https://www.cali.gov.co/planeacion/publicaciones/187380/revision-y-ajuste-del-plan-de-ordenamiento-territorial/?genPagdoc10013=4&genPagdoc10012=2&genPagdoc10014=1',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  2
),
(
  'Area Metropolitana del Suroccidente - AMSO',
  'Normativo',
  'Transversal',
  '2024',
  'Permanente',
  'Permanente',
  'https://drive.google.com/file/d/1oIWfjebTZGvKC2J-eOf58VSBVJ4f5zlg/view?usp=drive_link',
  'https://amsocali.com/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  3
),
(
  'Cali Distrito Especial Ley 1933 de 2018',
  'Normativo',
  'Transversal',
  '2023',
  '2050',
  'Permanente',
  'https://drive.google.com/file/d/18t8By1MvGaGj7Kh9ZiaMcdESKVx8LEus/view?usp=drive_link',
  'https://drive.google.com/file/d/18t8By1MvGaGj7Kh9ZiaMcdESKVx8LEus/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  4
),
(
  'Plan de Desarrollo Cali Capital Pacifica de Colombia',
  'Instrumentos Macro',
  'Transversal',
  '2024',
  '2027',
  'En Ejecución',
  'https://drive.google.com/file/d/1Pd2uT3IRprlCgMMO7JZpuHa5CwPvhjoV/view?usp=drive_link',
  'https://www.cali.gov.co/planeacion/publicaciones/186888/plan-de-desarrollo/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  5
),
(
  'Manual De Construccion Sostenible',
  'Documento Estratégico',
  'Territorio Adaptativo e Inteligente',
  '2023',
  'Permanente',
  'En Ejecución',
  'https://drive.google.com/file/d/1wBsbXUTiEt-E4fS70Ac5c33coK8l5_eM/view?usp=drive_link',
  'https://drive.google.com/file/d/1wBsbXUTiEt-E4fS70Ac5c33coK8l5_eM/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  6
),
(
  'Zonas De Influencia Economica Y Desarrollo',
  'Documento Estratégico',
  'Competitividad Sostenible',
  '2023',
  'Permanente',
  'En Ejecución',
  'https://drive.google.com/file/d/12aAPuxbKa8RUe-BeqKf9u-HkA5mSXCFs/view?usp=drive_link',
  'https://drive.google.com/file/d/12aAPuxbKa8RUe-BeqKf9u-HkA5mSXCFs/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  7
),
(
  'Politca Pública De Desarrollo Economico',
  'Política Pública',
  'Competitividad Sostenible',
  '2020',
  '2029',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1T7aD6ABhsoXEuNgp7cYMHxhbSwJviF8H/view?usp=drive_link',
  'https://drive.google.com/file/d/1T7aD6ABhsoXEuNgp7cYMHxhbSwJviF8H/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  8
),
(
  'PIMU- Plan Integral De Movilidad Urbana',
  'Plan',
  'Territorio Adaptativo e Inteligente',
  '2018',
  '2030',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1d9dL57_0fLjsKYUZECNvXqkt9KHpTnyE/view?usp=drive_link',
  'https://drive.google.com/file/d/1d9dL57_0fLjsKYUZECNvXqkt9KHpTnyE/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  9
),
(
  'Politica Pública De Turismo',
  'Política Pública',
  'Competitividad Sostenible',
  '2022',
  '2031',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1e4JH1julHjs0fWFiHsz_MoLnb7pWFCVz/view?usp=drive_link',
  'https://drive.google.com/file/d/1e4JH1julHjs0fWFiHsz_MoLnb7pWFCVz/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  10
),
(
  'Politica Pública Deporte Y Actividad Fisica',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2022',
  '2031',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1U22M0xXkmCgGfmroNcROwB8TbcOlAn5P/view?usp=drive_link',
  'https://drive.google.com/file/d/1U22M0xXkmCgGfmroNcROwB8TbcOlAn5P/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  11
),
(
  'Documento Estrategico Cluster Del Deporte- Vision',
  'Documento Estratégico',
  'Competitividad Sostenible',
  '2023',
  '2030',
  'En Ejecución',
  'https://drive.google.com/file/d/13xvefumsNu9qYsWqUbp0s-aftkpzm2W0/view?usp=drive_link',
  'https://drive.google.com/file/d/13xvefumsNu9qYsWqUbp0s-aftkpzm2W0/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  12
),
(
  'Politica Pública De Cultura Ciudadana',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2023',
  '2032',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/15z1fCfCgEx2EQDm4mUP3Ki2WQXm74oMs/view?usp=drive_link',
  'https://drive.google.com/file/d/15z1fCfCgEx2EQDm4mUP3Ki2WQXm74oMs/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  13
),
(
  'Plan De Restauración Ecologica',
  'Plan Maestro',
  'Territorio Adaptativo e Inteligente',
  '2016',
  '2050',
  'En Ejecución',
  'https://drive.google.com/file/d/1UiggKz_QORB5BGhH5tfI3sgXo0xgoav-/view?usp=drive_link',
  'https://archivo.minambiente.gov.co/index.php/bosques-biodiversidad-y-servicios-ecosistematicos/gestion-en-biodiversidad/restauracion-ecologica',
  null,
  '|',
  true,
  '[]'::jsonb,
  'excel',
  14
),
(
  'Política Publica de Seguridad Justicia y Convivencia',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2024',
  '2033',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1e3Oz0UMKcPNWbjwXU7ytDP0Czw-DEwrR/view?usp=drive_link',
  'https://www.cali.gov.co/seguridad/publicaciones/184455/politica-publica-de-seguridad-justicia-y-convivencia-ciudadana-de-santiago-de-cali-2024-2033/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  15
),
(
  'Politica Publica de Derechos Humanos',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2022',
  '2031',
  'En Ejecución - Mesa de Asistencia Técnica',
  'https://drive.google.com/file/d/1tn6o93wuiZTm4pXefEd7gQoQKZ7DcC59/view?usp=drive_link',
  'https://www.cali.gov.co/pazycultura/publicaciones/146279/politica-publica-de-derechos-humanos-y-dih-para-el-municipio-de-santiago-de-cali/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  16
),
(
  'Politica Pública CALI DIVERSIDAD',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2019',
  '2029',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1IKwNg_MMC7_CC0Baatr5N0TS2TOiTm9d/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/148606/politica-publica-calidiversidad/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  17
),
(
  'Política Pública Seguridad Alimentaria',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2019',
  '2029',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/11VhGLRcjdoAIqFPfS3XfGy1ycOop7tUh/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/172653/politica-publica-de-soberania-y-seguridad-alimentaria-y-nutricional/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  18
),
(
  'Polticica Pública de Juventudes',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2019',
  '2029',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1OHJ0QRsGtLAaYLOnZCvco_Bb1J42OP9E/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/180746/politica-publica-de-juventud-instrumento-fundamental-en-la-construccion-del-plan-de-desarrollo-de-cali/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  19
),
(
  'Política Pública Afrocolombiana negra y raizal de Santiago de Cali',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2019',
  '2029',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1hCQ21lSOvc95dfUp3LK9kBVj89gpwDbV/view?usp=drive_link',
  'http://cali.gov.co/bienestar/publicaciones/180746/politica-publica-de-juventud-instrumento-fundamental-en-la-construccion-del-plan-de-desarrollo-de-cali/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  20
),
(
  'Politica Publica de Envejecimiento y vejez',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2017',
  '2027',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1YhcyChNOxaZTSOY3HdB-MBJxTU_ja1Ob/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/172661/politica-publica-de-envejecimiento-y-vejez-para-las-personas-mayores/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  21
),
(
  'Politica Pública Habitante de Calle',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2019',
  '2028',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/161qqrVEzBbtd3BxF3mVeWYq9VkguAcal/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/162148/sistema-de-atencion-integral-para-el-habitante-de-la-calle/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  22
),
(
  'Política Pública Mujer',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2022',
  '2031',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/18GkJv9HZ4hvwFYSR1QjEocnQImAxmQGk/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/172656/politica-publica-reconocimiento-equidad-de-genero-e-igualdad-de-oportunidades-para-las-mujeres/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  23
),
(
  'Plan Municipal de Infraestructura Educativa',
  'Plan',
  'Bienestar Basado en la Interculturalidad',
  '2020',
  '2030',
  'En Ejecución',
  'https://drive.google.com/file/d/1INDEoIiSjidZXkLG3fgJW1BbOMPZqFxQ/view?usp=drive_link',
  'https://www.cali.gov.co/educacion/publicaciones/151242/plan-municipal-de-infraestructura-educativa/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  24
),
(
  'Retos para Trabajar la Calidad Educativa',
  'Documento Estratégico',
  'Bienestar Basado en la Interculturalidad',
  '2020',
  '2036',
  'En Ejecución',
  'https://drive.google.com/file/d/1y_iStEpm2GCtvUpvsgkFdQbfXbdRlpiq/view?usp=drive_link',
  'https://fundacionexe.org.co/document/retos-para-transformar-la-calidad-educativa-de-cali/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  25
),
(
  'Plan Territorial de Salud',
  'Plan',
  'Bienestar Basado en la Interculturalidad',
  '2024',
  '2027',
  'En Ejecución - Informes',
  'https://drive.google.com/file/d/1ZDj9FcB2L2gjr4VyQfIT6MIxy1asXYV8/view?usp=drive_link',
  'https://www.cali.gov.co/salud/publicaciones/49699/plan-territorial-de-salud-cali/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  26
),
(
  'Plan Integral de Gestios de Residuos Solidos PGIR',
  'Plan',
  'Territorio Adaptativo e Inteligente',
  '2015',
  '2027',
  'En Ejecución',
  'https://drive.google.com/file/d/164KgWiTqv0cNrjhvaTWqygaP8U9ZjR-L/view?usp=drive_link',
  'https://www.cali.gov.co/documentos/7925/plan-distrital-de-gestion-del-riesgo/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  27
),
(
  'Plan Distrital de Gestion de Riesgos y Desastres',
  'Plan',
  'Territorio Adaptativo e Inteligente',
  '2024',
  '2027',
  'En Ejecución',
  'https://drive.google.com/file/d/1XWkNbobE6nZ5B0Cqe7D0fWjOxEwtlzi3/view?usp=drive_link',
  'https://www.cali.gov.co/gestiondelriesgo/publicaciones/182649/plan-distrital-de-gestion-del-riesgo/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  28
),
(
  'Plan Integral de Seguridad y Convivencia Ciudadana',
  'Plan',
  'Bienestar Basado en la Interculturalidad',
  '2024',
  '2027',
  'En Ejecución - Informe',
  'https://drive.google.com/file/d/1h4MXMYd82gsuBPVdSM4x8aUbZ1oOlb1y/view?usp=drive_link',
  'https://www.cali.gov.co/seguridad/publicaciones/177212/plan-integral-de-seguridad-convivencia-ciudadana-y-justicia-pisccj/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  29
),
(
  'Politica Publica de Salud Mental',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2021',
  '2031',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1B5rL41zgByy9azSOH1NSjPHB8a8l0VZi/view?usp=drive_link',
  'https://www.cali.gov.co/salud/publicaciones/172620/politica-distrital-de-salud-mental-convivencia-social-y-abordaje-del-consumo-de-sustancias-psicoactivas/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  30
),
(
  'Política de Participación Social en Salud -PPSS-',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2024',
  '2027',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1j2L1OwS7vXWCyabY5vlyDyK0dPeU8q9i/view?usp=drive_link',
  'https://www.cali.gov.co/salud/publicaciones/167323/politica-de-participacion-social-en-salud-ppss/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  31
),
(
  'Plan de Ordenamiento y Manejo de la Cuenca Hidrografica',
  'Plan',
  'Territorio Adaptativo e Inteligente',
  '2022',
  '2036',
  'En Ejecución',
  'https://drive.google.com/file/d/1tX7F2JJkZkjchqlRVuG3O5IE30UCIsV9/view?usp=drive_link',
  'https://www.cali.gov.co/gestiondelriesgo/publicaciones/182651/plan-de-ordenacion-y-manejo-de-la-cuenca-hidrografica/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  32
),
(
  'Plan Especial de Salvaguardia Salsa',
  'Plan',
  'Bienestar Basado en la Interculturalidad',
  '2022',
  '2027',
  'En Ejecución',
  'https://drive.google.com/file/d/1Oguq9aJiX1CAmnuYdvEWlLFLnj5FDgR0/view?usp=drive_link',
  'https://www.mincultura.gov.co/direcciones/patrimonio-y-memoria/Documents/plan-especial-de-salvaguardia-complejo-salsa-calena-2022.pdf',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  33
),
(
  'Plan de Ordenamiento del Recurso Hidrico PORH Cali y Aguacatal',
  'Plan de Ordenamiento',
  'Territorio Adaptativo e Inteligente',
  '2024',
  '2043',
  'En Ejecución - Mesa',
  'https://drive.google.com/file/d/1tX7F2JJkZkjchqlRVuG3O5IE30UCIsV9/view?usp=drive_link',
  'https://www.cvc.gov.co/documentos/planes-y-programas/planes/planes-de-ordenamiento-del-recurso-hidrico-porh/porh-cali-y',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  34
),
(
  'Politica Publica Mejoramiento Integral Mi Habitat',
  'Política Pública',
  'Territorio Adaptativo e Inteligente',
  '2018',
  '2030',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/19DcZnG6ysQUeAVoMlkkCePYz93YXb0YH/view?usp=drive_link',
  'https://www.cali.gov.co/vivienda/publicaciones/172367/programa-mihabitat-politica-publica-de-mejoramiento-integral-del-habitat/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  35
),
(
  'Plan Especial De Manejo Y Protecion De Cali',
  'Plan',
  'Territorio Adaptativo e Inteligente',
  '2018',
  'Permanente',
  'En Ejecución - Observatorio',
  'https://drive.google.com/file/d/1Kwax6wizX27RPijAp4UEXfNGtpSYXsp8/view?usp=drive_link',
  'https://www.cali.gov.co/planeacion/publicaciones/187901/pemp-plan-especial-de-manejo-y-proteccion/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  36
),
(
  'Politica Pública Plan Indicativo- Atencion a la Discapacidad',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2025',
  '2025',
  'En Ejecución',
  'https://drive.google.com/file/d/1wk7FhUX9Qr_m198vnOKI6hTLrOqlEaIl/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/172657/politica-publica-de-atencion-a-la-discapacidad/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  37
),
(
  'Plan decenal de Cultura',
  'Plan',
  'Bienestar Basado en la Interculturalidad',
  '2018',
  '2028',
  'En Actualización - Observatorio',
  'https://drive.google.com/file/d/1VncyVwVP6vsFQDm6pzPeuborQq_-JbIh/view?usp=drive_link',
  'https://www.cali.gov.co/cultura/publicaciones/145592/plan-decenal-de-cultura-de-santiago-de-cali/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  38
),
(
  'Política Pública De Transición Energética Justa Y Comunidades Energética',
  'Política Pública',
  'Territorio Adaptativo e Inteligente',
  '2024',
  '2034',
  'En Actualización - Observatorio',
  'https://drive.google.com/file/d/1aiaEOaENiFlacelkWktW8OI3TCvhtbfz/view?usp=drive_link',
  'https://www.concejodecali.gov.co/publicaciones/60984/trazabilidad-proyectos-de-acuerdo-2024/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  39
),
(
  'Plan Cambio Climatico',
  'Plan',
  'Territorio Adaptativo e Inteligente',
  '2020',
  '2040',
  'En Actualización - Observatorio',
  'https://drive.google.com/file/d/1xEjgIyfWxfwvpQfZl5liGQ9YWv2jLdfB/view?usp=drive_link',
  'https://www.cali.gov.co/documentos/3047/cambio-climatico/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  40
),
(
  'Politica Publica de Educacion Ambiental',
  'Política Pública',
  'Territorio Adaptativo e Inteligente',
  '2017',
  '2036',
  'En Actualización',
  'https://drive.google.com/file/d/1nLpHW3oi800ssbTdSyfSO3S5GcrnBI1V/view?usp=drive_link',
  'https://www.cali.gov.co/aplicaciones/dagma/descargas/politica-publica-educacion-ambiental.pdf',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  41
),
(
  'Politica Publica Interespecie',
  'Política Pública',
  'Territorio Adaptativo e Inteligente',
  '2025',
  '2025',
  'En Actualización',
  'https://drive.google.com/file/d/1yJqkOdkrKbq2v9pIml_ebSDfL6Rn2TEw/view?usp=drive_link',
  'https://www.cali.gov.co/pazycultura/publicaciones/192654/historico-intervenciones-cali-con-sentido/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  42
),
(
  'Plan Indicativo Decenal Discapacidad',
  'Plan',
  'Bienestar Basado en la Interculturalidad',
  '2012',
  '2022',
  'En Actualización',
  'https://drive.google.com/file/d/1wk7FhUX9Qr_m198vnOKI6hTLrOqlEaIl/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/162469/conozca-el-marco-normativo-ley-que-rige-el-programa-discapacidad/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  43
),
(
  'Politica Publica Discapacidad',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2025',
  '2025',
  'En Actualización - Observatorio',
  'https://drive.google.com/file/d/1N-dH21-sIgP2XEH2o0Zi7jxPRz19pW-R/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/162469/conozca-el-marco-normativo-ley-que-rige-el-programa-discapacidad/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  44
),
(
  'Politica Publica Bilinguismo',
  'Política Pública',
  'Competitividad Sostenible',
  '2025',
  '2025',
  'En Actualización',
  'https://drive.google.com/file/d/1NXDoVITm37Nv6GCOvDpBgIrhL1PDmg_z/view?usp=drive_link',
  'https://www.ccc.org.co/inc/uploads/2022/09/GO-Cali.pdf',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  45
),
(
  'Plan Maestro De Servicios Publicos',
  'Plan Maestro',
  'Territorio Adaptativo e Inteligente',
  '2025',
  '2025',
  'En Actualización',
  'https://drive.google.com/file/d/1kJ0uQIIkInYtFu3rkOKvBKnmo0lPom5A/view?usp=drive_link',
  null,
  null,
  null,
  false,
  '["El campo enlace web es obligatorio."]'::jsonb,
  'excel',
  46
),
(
  'Plan Maestro De Vivienda',
  'Plan Maestro',
  'Territorio Adaptativo e Inteligente',
  '2025',
  '2025',
  'En Actualización',
  'https://www.cali.gov.co/documentos/6959/politica-publica-de-ctei/',
  null,
  null,
  null,
  false,
  '["El campo enlace web es obligatorio."]'::jsonb,
  'excel',
  47
),
(
  'Plan Maestro Cali Sostenible',
  'Plan Maestro',
  'Territorio Adaptativo e Inteligente',
  '2025',
  '2050',
  'En Actualización',
  'https://drive.google.com/file/d/1KbDpPU-qGKRia4GeZlppccPsCxws-8rF/view?usp=drive_link',
  'https://www.cali.gov.co/dagma/publicaciones/186489/plan-maestro-cali-sostenible/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  48
),
(
  'Plan de Ordenamiento Territorial',
  'Instrumentos Macro',
  'Transversal',
  '2014',
  '2038',
  'En Actualización - Expediente Municipal',
  'https://drive.google.com/drive/folders/1U2LMUJ-THZZe6VfmDiv1pEB7_SPNl1bC?usp=drive_link',
  'https://www.cali.gov.co/planeacion/publicaciones/187380/revision-y-ajuste-del-plan-de-ordenamiento-territorial/?genPagdoc10013=4&genPagdoc10012=2&genPagdoc10014=1',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  49
),
(
  'Politica-publica-para-la-regulacion-y-organizacion-del-espacio-publico/',
  'Política Pública',
  'Competitividad Sostenible',
  '2017',
  '2025',
  'En Actualización',
  'https://drive.google.com/file/d/11RaoDyyOSrViWAJ_hoYUJYRsBz4eL_11/view?usp=drive_link',
  'https://www.cali.gov.co/seguridad/publicaciones/135279/politica-publica-para-la-regulacion-y-organizacion-del-espacio-publico/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  50
),
(
  'Marco Fiscal de Mediano Plazo',
  'Instrumentos Macro',
  'Transversal',
  '2026',
  '2036',
  'En Actualización',
  'https://drive.google.com/file/d/1g_aWhIdXQPDk5sZ_YXw8vsBPqwpWsVFz/view?usp=drive_link',
  'https://www.cali.gov.co/documentos/1200/marco-fiscal-de-mediano-plazo/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  51
),
(
  'Plan Silvicultura- Estatuto de Silvicultura',
  'Plan',
  'Territorio Adaptativo e Inteligente',
  '2022',
  '2034',
  'En Actualización - GAMAU',
  'https://drive.google.com/file/d/12KKExkGQS_qHerFtG7Kbaj6qeHHOISxL/view?usp=drive_link',
  'https://drive.google.com/file/d/12KKExkGQS_qHerFtG7Kbaj6qeHHOISxL/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  52
),
(
  'Politica Pública Indigena',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2025',
  '2025',
  'En Actualización',
  'https://drive.google.com/file/d/1-RrD2REJJPA1EJ9kv2cEc5UgOT3g7qC2/view?usp=drive_link',
  'https://drive.google.com/file/d/12KKExkGQS_qHerFtG7Kbaj6qeHHOISxL/view?usp=drive_link',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  53
),
(
  'Catedra Ambiental',
  'Plan',
  'Territorio Adaptativo e Inteligente',
  '2025',
  'Permanente',
  'En Actualización',
  'https://drive.google.com/file/d/1oRN8dqaAwe0FBdOkupbx2O0YfMaK5Jnm/view?usp=drive_link',
  'https://www.concejodecali.gov.co/publicaciones/61222/cali-contara-con-catedra-ambiental-en-instituciones-educativas-oficiales/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  54
),
(
  'Politica Pública de Primera Infancia y Adolescencia',
  'Política Pública',
  'Bienestar Basado en la Interculturalidad',
  '2015',
  '2024',
  'Finalizada - Observatorio',
  'https://drive.google.com/file/d/1nn9027W8DTtuOXr9z8mgvPkQBuHFPNSf/view?usp=drive_link',
  'https://www.cali.gov.co/bienestar/publicaciones/184995/actualizacion-de-la-politica-publica-de-primera-infancia-en-cali-un-legado-social-que-se-construye-en-la-administracion-del-alcalde-eder/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  55
),
(
  'Política Pública de Ciencia y Tecnología',
  'Política Pública',
  'Competitividad Sostenible',
  '2024',
  '2034',
  'En Ejecución',
  'https://drive.google.com/file/d/1SVG0TxyZeeW_MI3wpmlBltTQwUsjXmIl/view?usp=drive_link',
  'https://www.cali.gov.co/documentos/6959/politica-publica-de-ctei/',
  null,
  null,
  true,
  '[]'::jsonb,
  'excel',
  56
)
on conflict do nothing;
