SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS instrumentos_planeacion;
DROP TABLE IF EXISTS admin_users;

CREATE TABLE admin_users (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  password_hash TEXT NOT NULL,
  nombre VARCHAR(255) NOT NULL DEFAULT 'Administrador',
  activo TINYINT(1) NOT NULL DEFAULT 1,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY admin_users_email_key (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE instrumentos_planeacion (
  id INT NOT NULL AUTO_INCREMENT,
  nombre TEXT NOT NULL,
  tipo VARCHAR(255) NOT NULL DEFAULT '',
  eje VARCHAR(255) NOT NULL DEFAULT '',
  fecha_inicio VARCHAR(50) NOT NULL DEFAULT '',
  fecha_fin VARCHAR(50) NOT NULL DEFAULT '',
  estado VARCHAR(255) NOT NULL DEFAULT '',
  link TEXT NOT NULL,
  enlace_web TEXT NOT NULL,
  documento_url TEXT NOT NULL,
  observatorio TEXT NOT NULL,
  visible TINYINT(1) NOT NULL DEFAULT 0,
  validacion_errores JSON NOT NULL,
  origen VARCHAR(255) NOT NULL DEFAULT 'admin',
  source_row INT NULL,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY instrumentos_visible_idx (visible),
  KEY instrumentos_fecha_actualizacion_idx (fecha_actualizacion)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO admin_users (id, email, password_hash, nombre, activo, fecha_creacion) VALUES (1, 'admin@cali500.com.co', 'scrypt:7d1c8da1779420a1e8dcece491601e61:491c0299109263aee6cd804fe83afef5673d878ae9ce023618e050f2d82cf42a76a182517f5b6724aee31be93439e150ca217eff79be9699711eea62e02e490b', 'Administrador Cali 500', 1, '2026-06-05 18:48:31');
INSERT INTO admin_users (id, email, password_hash, nombre, activo, fecha_creacion) VALUES (2, 'editor@cali500.com.co', 'scrypt:171add4e2a36e261ab036a58bc227951:e232ea537e9ce6dd80cc32dfb714ecdfd5ffeba651a111deccc2f9d5897a0e832ab1333cafa94dd2fb8d6de9793d2dc5ccecd6710ba968bf058c77d524e752ad', 'Editor Cali 500', 1, '2026-06-05 18:51:04');

INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (2, 'VISION CALI 500+', 'Instrumentos Macro', 'Transversal', '2024', '2050', 'En Ejecución', '0.VISION CALI 500+.pdf', 'https://www.cali.gov.co/planeacion/publicaciones/187380/revision-y-ajuste-del-plan-de-ordenamiento-territorial/?genPagdoc10013=4&genPagdoc10012=2&genPagdoc10014=1', '', '', 1, '[]', 'excel:hoja-1', 2, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (3, 'Area Metropolitana del Suroccidente - AMSO', 'Normativo', 'Transversal', '2024', 'Permanente', 'Permanente', 'https://drive.google.com/file/d/1oIWfjebTZGvKC2J-eOf58VSBVJ4f5zlg/view?usp=drive_link', 'https://amsocali.com/', '', '', 1, '[]', 'excel:hoja-1', 3, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (4, 'Cali Distrito Especial Ley 1933 de 2018', 'Normativo', 'Transversal', '2023', '2050', 'Permanente', 'https://drive.google.com/file/d/18t8By1MvGaGj7Kh9ZiaMcdESKVx8LEus/view?usp=drive_link', 'https://drive.google.com/file/d/18t8By1MvGaGj7Kh9ZiaMcdESKVx8LEus/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 4, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (5, 'Plan de Desarrollo Cali Capital Pacifica de Colombia', 'Instrumentos Macro', 'Transversal', '2024', '2027', 'En Ejecución', 'https://drive.google.com/file/d/1Pd2uT3IRprlCgMMO7JZpuHa5CwPvhjoV/view?usp=drive_link', 'https://www.cali.gov.co/planeacion/publicaciones/186888/plan-de-desarrollo/', '', '', 1, '[]', 'excel:hoja-1', 5, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (6, 'Manual De Construccion Sostenible', 'Documento Estratégico', 'Territorio Adaptativo e Inteligente', '2023', 'Permanente', 'En Ejecución', 'https://drive.google.com/file/d/1wBsbXUTiEt-E4fS70Ac5c33coK8l5_eM/view?usp=drive_link', 'https://drive.google.com/file/d/1wBsbXUTiEt-E4fS70Ac5c33coK8l5_eM/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 6, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (7, 'Zonas De Influencia Economica Y Desarrollo', 'Documento Estratégico', 'Competitividad Sostenible', '2023', 'Permanente', 'En Ejecución', 'https://drive.google.com/file/d/12aAPuxbKa8RUe-BeqKf9u-HkA5mSXCFs/view?usp=drive_link', 'https://drive.google.com/file/d/12aAPuxbKa8RUe-BeqKf9u-HkA5mSXCFs/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 7, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (8, 'Politca Pública De Desarrollo Economico', 'Política Pública', 'Competitividad Sostenible', '2020', '2029', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1T7aD6ABhsoXEuNgp7cYMHxhbSwJviF8H/view?usp=drive_link', 'https://drive.google.com/file/d/1T7aD6ABhsoXEuNgp7cYMHxhbSwJviF8H/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 8, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (9, 'PIMU- Plan Integral De Movilidad Urbana', 'Plan', 'Territorio Adaptativo e Inteligente', '2018', '2030', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1d9dL57_0fLjsKYUZECNvXqkt9KHpTnyE/view?usp=drive_link', 'https://drive.google.com/file/d/1d9dL57_0fLjsKYUZECNvXqkt9KHpTnyE/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 9, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (10, 'Politica Pública De Turismo', 'Política Pública', 'Competitividad Sostenible', '2022', '2031', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1e4JH1julHjs0fWFiHsz_MoLnb7pWFCVz/view?usp=drive_link', 'https://drive.google.com/file/d/1e4JH1julHjs0fWFiHsz_MoLnb7pWFCVz/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 10, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (11, 'Politica Pública Deporte Y Actividad Fisica', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2022', '2031', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1U22M0xXkmCgGfmroNcROwB8TbcOlAn5P/view?usp=drive_link', 'https://drive.google.com/file/d/1U22M0xXkmCgGfmroNcROwB8TbcOlAn5P/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 11, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (12, 'Documento Estrategico Cluster Del Deporte- Vision', 'Documento Estratégico', 'Competitividad Sostenible', '2023', '2030', 'En Ejecución', 'https://drive.google.com/file/d/13xvefumsNu9qYsWqUbp0s-aftkpzm2W0/view?usp=drive_link', 'https://drive.google.com/file/d/13xvefumsNu9qYsWqUbp0s-aftkpzm2W0/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 12, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (13, 'Politica Pública De Cultura Ciudadana', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2023', '2032', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/15z1fCfCgEx2EQDm4mUP3Ki2WQXm74oMs/view?usp=drive_link', 'https://drive.google.com/file/d/15z1fCfCgEx2EQDm4mUP3Ki2WQXm74oMs/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 13, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (14, 'Plan De Restauración Ecologica', 'Plan Maestro', 'Territorio Adaptativo e Inteligente', '2016', '2050', 'En Ejecución', 'https://drive.google.com/file/d/1UiggKz_QORB5BGhH5tfI3sgXo0xgoav-/view?usp=drive_link', 'https://archivo.minambiente.gov.co/index.php/bosques-biodiversidad-y-servicios-ecosistematicos/gestion-en-biodiversidad/restauracion-ecologica', '', '|', 1, '[]', 'excel:hoja-1', 14, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (15, 'Política Publica de Seguridad Justicia y Convivencia', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2024', '2033', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1e3Oz0UMKcPNWbjwXU7ytDP0Czw-DEwrR/view?usp=drive_link', 'https://www.cali.gov.co/seguridad/publicaciones/184455/politica-publica-de-seguridad-justicia-y-convivencia-ciudadana-de-santiago-de-cali-2024-2033/', '', '', 1, '[]', 'excel:hoja-1', 15, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (16, 'Politica Publica de Derechos Humanos', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2022', '2031', 'En Ejecución - Mesa de Asistencia Técnica', 'https://drive.google.com/file/d/1tn6o93wuiZTm4pXefEd7gQoQKZ7DcC59/view?usp=drive_link', 'https://www.cali.gov.co/pazycultura/publicaciones/146279/politica-publica-de-derechos-humanos-y-dih-para-el-municipio-de-santiago-de-cali/', '', '', 1, '[]', 'excel:hoja-1', 16, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (17, 'Politica Pública CALI DIVERSIDAD', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2019', '2029', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1IKwNg_MMC7_CC0Baatr5N0TS2TOiTm9d/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/148606/politica-publica-calidiversidad/', '', '', 1, '[]', 'excel:hoja-1', 17, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (18, 'Política Pública Seguridad Alimentaria', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2019', '2029', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/11VhGLRcjdoAIqFPfS3XfGy1ycOop7tUh/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/172653/politica-publica-de-soberania-y-seguridad-alimentaria-y-nutricional/', '', '', 1, '[]', 'excel:hoja-1', 18, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (19, 'Polticica Pública de Juventudes', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2019', '2029', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1OHJ0QRsGtLAaYLOnZCvco_Bb1J42OP9E/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/180746/politica-publica-de-juventud-instrumento-fundamental-en-la-construccion-del-plan-de-desarrollo-de-cali/', '', '', 1, '[]', 'excel:hoja-1', 19, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (20, 'Política Pública Afrocolombiana negra y raizal de Santiago de Cali', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2019', '2029', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1hCQ21lSOvc95dfUp3LK9kBVj89gpwDbV/view?usp=drive_link', 'http://cali.gov.co/bienestar/publicaciones/180746/politica-publica-de-juventud-instrumento-fundamental-en-la-construccion-del-plan-de-desarrollo-de-cali/', '', '', 1, '[]', 'excel:hoja-1', 20, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (21, 'Politica Publica de Envejecimiento y vejez', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2017', '2027', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1YhcyChNOxaZTSOY3HdB-MBJxTU_ja1Ob/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/172661/politica-publica-de-envejecimiento-y-vejez-para-las-personas-mayores/', '', '', 1, '[]', 'excel:hoja-1', 21, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (22, 'Politica Pública Habitante de Calle', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2019', '2028', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/161qqrVEzBbtd3BxF3mVeWYq9VkguAcal/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/162148/sistema-de-atencion-integral-para-el-habitante-de-la-calle/', '', '', 1, '[]', 'excel:hoja-1', 22, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (23, 'Política Pública Mujer', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2022', '2031', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/18GkJv9HZ4hvwFYSR1QjEocnQImAxmQGk/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/172656/politica-publica-reconocimiento-equidad-de-genero-e-igualdad-de-oportunidades-para-las-mujeres/', '', '', 1, '[]', 'excel:hoja-1', 23, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (24, 'Plan Municipal de Infraestructura Educativa', 'Plan', 'Bienestar Basado en la Interculturalidad', '2020', '2030', 'En Ejecución', 'https://drive.google.com/file/d/1INDEoIiSjidZXkLG3fgJW1BbOMPZqFxQ/view?usp=drive_link', 'https://www.cali.gov.co/educacion/publicaciones/151242/plan-municipal-de-infraestructura-educativa/', '', '', 1, '[]', 'excel:hoja-1', 24, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (25, 'Retos para Trabajar la Calidad Educativa', 'Documento Estratégico', 'Bienestar Basado en la Interculturalidad', '2020', '2036', 'En Ejecución', 'https://drive.google.com/file/d/1y_iStEpm2GCtvUpvsgkFdQbfXbdRlpiq/view?usp=drive_link', 'https://fundacionexe.org.co/document/retos-para-transformar-la-calidad-educativa-de-cali/', '', '', 1, '[]', 'excel:hoja-1', 25, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (26, 'Plan Territorial de Salud', 'Plan', 'Bienestar Basado en la Interculturalidad', '2024', '2027', 'En Ejecución - Informes', 'https://drive.google.com/file/d/1ZDj9FcB2L2gjr4VyQfIT6MIxy1asXYV8/view?usp=drive_link', 'https://www.cali.gov.co/salud/publicaciones/49699/plan-territorial-de-salud-cali/', '', '', 1, '[]', 'excel:hoja-1', 26, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (27, 'Plan Integral de Gestios de Residuos Solidos PGIR', 'Plan', 'Territorio Adaptativo e Inteligente', '2015', '2027', 'En Ejecución', 'https://drive.google.com/file/d/164KgWiTqv0cNrjhvaTWqygaP8U9ZjR-L/view?usp=drive_link', 'https://www.cali.gov.co/documentos/7925/plan-distrital-de-gestion-del-riesgo/', '', '', 1, '[]', 'excel:hoja-1', 27, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (28, 'Plan Distrital de Gestion de Riesgos y Desastres', 'Plan', 'Territorio Adaptativo e Inteligente', '2024', '2027', 'En Ejecución', 'https://drive.google.com/file/d/1XWkNbobE6nZ5B0Cqe7D0fWjOxEwtlzi3/view?usp=drive_link', 'https://www.cali.gov.co/gestiondelriesgo/publicaciones/182649/plan-distrital-de-gestion-del-riesgo/', '', '', 1, '[]', 'excel:hoja-1', 28, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (29, 'Plan Integral de Seguridad y Convivencia Ciudadana', 'Plan', 'Bienestar Basado en la Interculturalidad', '2024', '2027', 'En Ejecución - Informe', 'https://drive.google.com/file/d/1h4MXMYd82gsuBPVdSM4x8aUbZ1oOlb1y/view?usp=drive_link', 'https://www.cali.gov.co/seguridad/publicaciones/177212/plan-integral-de-seguridad-convivencia-ciudadana-y-justicia-pisccj/', '', '', 1, '[]', 'excel:hoja-1', 29, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (30, 'Politica Publica de Salud Mental', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2021', '2031', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1B5rL41zgByy9azSOH1NSjPHB8a8l0VZi/view?usp=drive_link', 'https://www.cali.gov.co/salud/publicaciones/172620/politica-distrital-de-salud-mental-convivencia-social-y-abordaje-del-consumo-de-sustancias-psicoactivas/', '', '', 1, '[]', 'excel:hoja-1', 30, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (31, 'Política de Participación Social en Salud -PPSS-', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2024', '2027', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1j2L1OwS7vXWCyabY5vlyDyK0dPeU8q9i/view?usp=drive_link', 'https://www.cali.gov.co/salud/publicaciones/167323/politica-de-participacion-social-en-salud-ppss/', '', '', 1, '[]', 'excel:hoja-1', 31, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (32, 'Plan de Ordenamiento y Manejo de la Cuenca Hidrografica', 'Plan', 'Territorio Adaptativo e Inteligente', '2022', '2036', 'En Ejecución', 'https://drive.google.com/file/d/1tX7F2JJkZkjchqlRVuG3O5IE30UCIsV9/view?usp=drive_link', 'https://www.cali.gov.co/gestiondelriesgo/publicaciones/182651/plan-de-ordenacion-y-manejo-de-la-cuenca-hidrografica/', '', '', 1, '[]', 'excel:hoja-1', 32, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (33, 'Plan Especial de Salvaguardia Salsa', 'Plan', 'Bienestar Basado en la Interculturalidad', '2022', '2027', 'En Ejecución', 'https://drive.google.com/file/d/1Oguq9aJiX1CAmnuYdvEWlLFLnj5FDgR0/view?usp=drive_link', 'https://www.mincultura.gov.co/direcciones/patrimonio-y-memoria/Documents/plan-especial-de-salvaguardia-complejo-salsa-calena-2022.pdf', '', '', 1, '[]', 'excel:hoja-1', 33, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (34, 'Plan de Ordenamiento del Recurso Hidrico PORH Cali y Aguacatal', 'Plan de Ordenamiento', 'Territorio Adaptativo e Inteligente', '2024', '2043', 'En Ejecución - Mesa', 'https://drive.google.com/file/d/1tX7F2JJkZkjchqlRVuG3O5IE30UCIsV9/view?usp=drive_link', 'https://www.cvc.gov.co/documentos/planes-y-programas/planes/planes-de-ordenamiento-del-recurso-hidrico-porh/porh-cali-y', '', '', 1, '[]', 'excel:hoja-1', 34, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (35, 'Politica Publica Mejoramiento Integral Mi Habitat', 'Política Pública', 'Territorio Adaptativo e Inteligente', '2018', '2030', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/19DcZnG6ysQUeAVoMlkkCePYz93YXb0YH/view?usp=drive_link', 'https://www.cali.gov.co/vivienda/publicaciones/172367/programa-mihabitat-politica-publica-de-mejoramiento-integral-del-habitat/', '', '', 1, '[]', 'excel:hoja-1', 35, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (36, 'Plan Especial De Manejo Y Protecion De Cali', 'Plan', 'Territorio Adaptativo e Inteligente', '2018', 'Permanente', 'En Ejecución - Observatorio', 'https://drive.google.com/file/d/1Kwax6wizX27RPijAp4UEXfNGtpSYXsp8/view?usp=drive_link', 'https://www.cali.gov.co/planeacion/publicaciones/187901/pemp-plan-especial-de-manejo-y-proteccion/', '', '', 1, '[]', 'excel:hoja-1', 36, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (37, 'Politica Pública Plan Indicativo- Atencion a la Discapacidad', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2025', '2025', 'En Ejecución', 'https://drive.google.com/file/d/1wk7FhUX9Qr_m198vnOKI6hTLrOqlEaIl/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/172657/politica-publica-de-atencion-a-la-discapacidad/', '', '', 1, '[]', 'excel:hoja-1', 37, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (38, 'Plan decenal de Cultura', 'Plan', 'Bienestar Basado en la Interculturalidad', '2018', '2028', 'En Actualización - Observatorio', 'https://drive.google.com/file/d/1VncyVwVP6vsFQDm6pzPeuborQq_-JbIh/view?usp=drive_link', 'https://www.cali.gov.co/cultura/publicaciones/145592/plan-decenal-de-cultura-de-santiago-de-cali/', '', '', 1, '[]', 'excel:hoja-1', 38, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (39, 'Política Pública De Transición Energética Justa Y Comunidades Energética', 'Política Pública', 'Territorio Adaptativo e Inteligente', '2024', '2034', 'En Actualización - Observatorio', 'https://drive.google.com/file/d/1aiaEOaENiFlacelkWktW8OI3TCvhtbfz/view?usp=drive_link', 'https://www.concejodecali.gov.co/publicaciones/60984/trazabilidad-proyectos-de-acuerdo-2024/', '', '', 1, '[]', 'excel:hoja-1', 39, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (40, 'Plan Cambio Climatico', 'Plan', 'Territorio Adaptativo e Inteligente', '2020', '2040', 'En Actualización - Observatorio', 'https://drive.google.com/file/d/1xEjgIyfWxfwvpQfZl5liGQ9YWv2jLdfB/view?usp=drive_link', 'https://www.cali.gov.co/documentos/3047/cambio-climatico/', '', '', 1, '[]', 'excel:hoja-1', 40, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (41, 'Politica Publica de Educacion Ambiental', 'Política Pública', 'Territorio Adaptativo e Inteligente', '2017', '2036', 'En Actualización', 'https://drive.google.com/file/d/1nLpHW3oi800ssbTdSyfSO3S5GcrnBI1V/view?usp=drive_link', 'https://www.cali.gov.co/aplicaciones/dagma/descargas/politica-publica-educacion-ambiental.pdf', '', '', 1, '[]', 'excel:hoja-1', 41, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (42, 'Politica Publica Interespecie', 'Política Pública', 'Territorio Adaptativo e Inteligente', '2025', '2025', 'En Actualización', 'https://drive.google.com/file/d/1yJqkOdkrKbq2v9pIml_ebSDfL6Rn2TEw/view?usp=drive_link', 'https://www.cali.gov.co/pazycultura/publicaciones/192654/historico-intervenciones-cali-con-sentido/', '', '', 1, '[]', 'excel:hoja-1', 42, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (43, 'Plan Indicativo Decenal Discapacidad', 'Plan', 'Bienestar Basado en la Interculturalidad', '2012', '2022', 'En Actualización', 'https://drive.google.com/file/d/1wk7FhUX9Qr_m198vnOKI6hTLrOqlEaIl/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/162469/conozca-el-marco-normativo-ley-que-rige-el-programa-discapacidad/', '', '', 1, '[]', 'excel:hoja-1', 43, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (44, 'Politica Publica Discapacidad', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2025', '2025', 'En Actualización - Observatorio', 'https://drive.google.com/file/d/1N-dH21-sIgP2XEH2o0Zi7jxPRz19pW-R/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/162469/conozca-el-marco-normativo-ley-que-rige-el-programa-discapacidad/', '', '', 1, '[]', 'excel:hoja-1', 44, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (45, 'Politica Publica Bilinguismo', 'Política Pública', 'Competitividad Sostenible', '2025', '2025', 'En Actualización', 'https://drive.google.com/file/d/1NXDoVITm37Nv6GCOvDpBgIrhL1PDmg_z/view?usp=drive_link', 'https://www.ccc.org.co/inc/uploads/2022/09/GO-Cali.pdf', '', '', 1, '[]', 'excel:hoja-1', 45, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (46, 'Plan Maestro De Servicios Publicos', 'Plan Maestro', 'Territorio Adaptativo e Inteligente', '2025', '2025', 'En Actualización', 'https://drive.google.com/file/d/1kJ0uQIIkInYtFu3rkOKvBKnmo0lPom5A/view?usp=drive_link', '', '', '', 0, '["El campo enlace web es obligatorio."]', 'excel:hoja-1', 46, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (47, 'Plan Maestro De Vivienda', 'Plan Maestro', 'Territorio Adaptativo e Inteligente', '2025', '2025', 'En Actualización', 'https://www.cali.gov.co/documentos/6959/politica-publica-de-ctei/', '', '', '', 0, '["El campo enlace web es obligatorio."]', 'excel:hoja-1', 47, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (48, 'Plan Maestro Cali Sostenible', 'Plan Maestro', 'Territorio Adaptativo e Inteligente', '2025', '2050', 'En Actualización', 'https://drive.google.com/file/d/1KbDpPU-qGKRia4GeZlppccPsCxws-8rF/view?usp=drive_link', 'https://www.cali.gov.co/dagma/publicaciones/186489/plan-maestro-cali-sostenible/', '', '', 1, '[]', 'excel:hoja-1', 48, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (49, 'Plan de Ordenamiento Territorial', 'Instrumentos Macro', 'Transversal', '2014', '2038', 'En Actualización - Expediente Municipal', 'https://drive.google.com/drive/folders/1U2LMUJ-THZZe6VfmDiv1pEB7_SPNl1bC?usp=drive_link', 'https://www.cali.gov.co/planeacion/publicaciones/187380/revision-y-ajuste-del-plan-de-ordenamiento-territorial/?genPagdoc10013=4&genPagdoc10012=2&genPagdoc10014=1', '', '', 1, '[]', 'excel:hoja-1', 49, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (50, 'Politica-publica-para-la-regulacion-y-organizacion-del-espacio-publico/', 'Política Pública', 'Competitividad Sostenible', '2017', '2025', 'En Actualización', 'https://drive.google.com/file/d/11RaoDyyOSrViWAJ_hoYUJYRsBz4eL_11/view?usp=drive_link', 'https://www.cali.gov.co/seguridad/publicaciones/135279/politica-publica-para-la-regulacion-y-organizacion-del-espacio-publico/', '', '', 1, '[]', 'excel:hoja-1', 50, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (51, 'Marco Fiscal de Mediano Plazo', 'Instrumentos Macro', 'Transversal', '2026', '2036', 'En Actualización', 'https://drive.google.com/file/d/1g_aWhIdXQPDk5sZ_YXw8vsBPqwpWsVFz/view?usp=drive_link', 'https://www.cali.gov.co/documentos/1200/marco-fiscal-de-mediano-plazo/', '', '', 1, '[]', 'excel:hoja-1', 51, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (52, 'Plan Silvicultura- Estatuto de Silvicultura', 'Plan', 'Territorio Adaptativo e Inteligente', '2022', '2034', 'En Actualización - GAMAU', 'https://drive.google.com/file/d/12KKExkGQS_qHerFtG7Kbaj6qeHHOISxL/view?usp=drive_link', 'https://drive.google.com/file/d/12KKExkGQS_qHerFtG7Kbaj6qeHHOISxL/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 52, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (53, 'Politica Pública Indigena', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2025', '2025', 'En Actualización', 'https://drive.google.com/file/d/1-RrD2REJJPA1EJ9kv2cEc5UgOT3g7qC2/view?usp=drive_link', 'https://drive.google.com/file/d/12KKExkGQS_qHerFtG7Kbaj6qeHHOISxL/view?usp=drive_link', '', '', 1, '[]', 'excel:hoja-1', 53, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (54, 'Catedra Ambiental', 'Plan', 'Territorio Adaptativo e Inteligente', '2025', 'Permanente', 'En Actualización', 'https://drive.google.com/file/d/1oRN8dqaAwe0FBdOkupbx2O0YfMaK5Jnm/view?usp=drive_link', 'https://www.concejodecali.gov.co/publicaciones/61222/cali-contara-con-catedra-ambiental-en-instituciones-educativas-oficiales/', '', '', 1, '[]', 'excel:hoja-1', 54, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (55, 'Politica Pública de Primera Infancia y Adolescencia', 'Política Pública', 'Bienestar Basado en la Interculturalidad', '2015', '2024', 'Finalizada - Observatorio', 'https://drive.google.com/file/d/1nn9027W8DTtuOXr9z8mgvPkQBuHFPNSf/view?usp=drive_link', 'https://www.cali.gov.co/bienestar/publicaciones/184995/actualizacion-de-la-politica-publica-de-primera-infancia-en-cali-un-legado-social-que-se-construye-en-la-administracion-del-alcalde-eder/', '', '', 1, '[]', 'excel:hoja-1', 55, '2026-06-05 19:09:53', '2026-06-05 19:09:53');
INSERT INTO instrumentos_planeacion (id, nombre, tipo, eje, fecha_inicio, fecha_fin, estado, link, enlace_web, documento_url, observatorio, visible, validacion_errores, origen, source_row, fecha_creacion, fecha_actualizacion) VALUES (56, 'Política Pública de Ciencia y Tecnología', 'Política Pública', 'Competitividad Sostenible', '2024', '2034', 'En Ejecución', 'https://drive.google.com/file/d/1SVG0TxyZeeW_MI3wpmlBltTQwUsjXmIl/view?usp=drive_link', 'https://www.cali.gov.co/documentos/6959/politica-publica-de-ctei/', '', '', 1, '[]', 'excel:hoja-1', 56, '2026-06-05 19:09:53', '2026-06-05 19:09:53');

SET FOREIGN_KEY_CHECKS = 1;
